export const START_PEERJS = "START_PEERJS";
export const START_MEETING = "START_MEETING";
export const JOIN_EXISTING_MEETING = "JOIN_EXISTING_MEETING";
export const ADD_VIDEO_TO_LIST = "ADD_VIDEO_TO_LIST";
export const SET_MY_PEER_NAME = "SET_MY_NAME";
export const SET_HOST = "SET_HOST";

export const ADD_CLIENT_TO_LIST = "ADD_CLIENT_TO_LIST";
export const ADD_CALL_TO_LIST = "ADD_CALL_TO_LIST";
export const REMOVE_CLIENT_FROM_LIST = "REMOVE_CLIENT_FROM_LIST";
export const REMOVE_CALL_FROM_LIST = "REMOVE_CALL_FROM_LIST";
export const SET_MY_PEER_ID = "SET_MY_PEER_ID";

