export const NEW_MEETING = "NEW_MEETING";
export const JOIN_MEETING = "JOIN_MEETING";
export const REJOIN_MEETING = "REJOIN_MEETING";
export const OPEN_HELP_INTRO = "OPEN_HELP_INTRO";
export const OPEN_FEEDBACK_INTRO = "OPEN_FEEDBACK_INTRO";
export const OPEN_SETTINGS_INTRO = "OPEN_SETTINGS_INTRO";
export const OPEN_APPS_INTRO = "OPEN_APPS_INTRO";
export const OPEN_ACCOUNT_INTRO = "OPEN_ACCOUNT_INTRO";
export const LEFT_ARROW_INTRO = "LEFT_ARROW_INTRO";
export const RIGHT_ARROW_INTRO = "RIGHT_ARROW_INTRO";
export const LEARN_MORE_INTRO = "LEARN_MORE_INTRO";

export const CLOSE_SIDEBOX = "CLOSE_SIDEBOX";
export const SEND_MESSAGE = "SEND_MESSAGE";
export const MUTE_MIC = "MUTE_MIC";
export const UNMUTE_MIC = "UNMUTE_MIC";
export const MUTE_VIDEO = "MUTE_VIDEO";
export const UNMUTE_VIDEO = "UNMUTE_VIDEO";
export const CC_TURNOFF = "CC_TURNOFF";
export const CC_TURNON = "CC_TURNON";
export const OPEN_OPTIONS_PRESENTATION = "OPEN_OPTIONS_PRESENTATION";
export const OPEN_OPTIONS_MORE = "OPEN_OPTIONS_MORE";
export const END_CALL = "END_CALL";

export const ADD_MEMBERS = "ADD_MEMBERS";
export const COPY_LINK = "COPY_LINK";
export const CLOSE_ADD_MEMBERS_BOX = "CLOSE_ADD_MEMBERS_BOX";

export const MEETING_DETAILS = "MEETING_DETAILS";
export const OPEN_MEMBERS_BOX = "OPEN_MEMBERS_BOX";
export const OPEN_CHAT_BOX = "OPEN_CHAT_BOX";
export const OPEN_ACTIVITIES_BOX = "OPEN_ACTIVITIES_BOX";
export const OPEN_SECURITY_BOX = "OPEN_SECURITY_BOX";
export const GOTO_HOME_PAGE = "GOTO_HOME_PAGE";

export const SET_MY_NAME = "SET_MY_NAME";
export const UPDATE_CONVERSATION = "UPDATE_CONVERSATION";
